import sys, os
from collections import defaultdict
if len(sys.argv) < 3:
    print('Usage: python generate_pot.py <output dir> <input dir 1> <input dir 2> ...')
    sys.exit(1)

import escaped_bytes
def escape_string(s):
    for char, repl in escaped_bytes.escaped_bytes.items():
        s = s.replace(char, repl)
    return s

translations = defaultdict(list)
for src in sys.argv[2:]:
    for root, dirs, files in os.walk(src):
        for file in files:
            if file.lower().endswith('.mst'):
                file_path = os.path.join(root, file)
                translations[file].append(open(file_path, 'r', encoding='utf-8').readlines())
for file, lines in translations.items():
    file_path = os.path.join(sys.argv[1], file.split('.')[0] + '.po')
    with open(file_path, 'w', encoding='utf-8') as output:
        output.write(r'''# THIS FILE IS AUTOMATICALLY GENERATED BY generate_po.py.
"Project-Id-Version: CHAOS;HEAD NOAH SIMPLIFIED CHINESE TRANSLATION PROJECT\n"
"POT-Creation-Date: \n"
"PO-Revision-Date: \n"
"Last-Translator: \n"
"Language-Team: mos9527\n"
"Language: zh_CN\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

''')
        for line in range(0, len(lines[0])):
            if len(lines) != 1:
                output.write('msgid "%s"\n' % escape_string(lines[0][line].strip()))
                output.write('msgstr "%s"\n' % escape_string(lines[1][line].strip()))
            else:
                output.write('msgid "%s"\n' % escape_string(lines[0][line].strip()))
                output.write('msgstr "%s"\n' % escape_string(lines[0][line].strip()))
            output.write('\n')
